# FUNDING

github: [devinschumacher]
liberapay: devinschumacher
open_collective: devinschumacher
custom: [
"https://devinschumacher.com",
"https://serp.co",
"https://serp.ai",
"https://serptools.github.io",
"https://serpdownloaders.github.io",
"https://serp.media",
]
